services:
  mysql:
    image: mysql:8.0
    container_name: mysql-pokedex
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokedex_db
    ports:
      - "3355:3306"
    volumes:
      - mysql_pokedex_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-pokedex
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8095:80"
    depends_on:
      - mysql

volumes:
  mysql_pokedex_data:
